services:
  - type: static
    name: Tracking-website
    buildCommand: node build.js
    staticPublishPath: ./dist
  - type: web
    name: Tracking-website-service
    env: node
    buildCommand: node build.js
    startCommand: cd backend && node src/server.js
    envVars:
      - key: BREVO_API_KEY
        sync: false
      - key: MONGODB_URI
        value: mongodb+srv://mbahemile35_db_user:pFu4mN7A4zTNLdqm@cluster1.4mor1fj.mongodb.net/ups_portal?retryWrites=true&w=majority&appName=Cluster1
